# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 07:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('image', models.CharField(max_length=500)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('performance_rating', models.IntegerField()),
                ('build_rating', models.IntegerField()),
                ('camera_rating', models.IntegerField()),
                ('price_rating', models.IntegerField()),
                ('dimensions', models.CharField(max_length=100)),
                ('weight', models.CharField(max_length=50)),
                ('display', models.CharField(max_length=100)),
                ('os', models.CharField(max_length=50)),
                ('chipset', models.CharField(max_length=100)),
                ('memory', models.CharField(max_length=100)),
                ('camera', models.CharField(max_length=100)),
                ('battery', models.CharField(max_length=100)),
                ('brand', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='devices.Brand')),
            ],
        ),
    ]
