# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 07:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.Brand'),
        ),
    ]
