# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 11:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_auto_20161222_0820'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='brand',
            name='os',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.Os'),
        ),
    ]
