# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-26 17:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_auto_20161222_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='os',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.Os'),
        ),
    ]
