# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-26 18:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0009_auto_20161226_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='is_tablet',
            field=models.CharField(choices=[('PH', 'Phone'), ('TB', 'Tablet')], default='PH', max_length=2),
        ),
        migrations.AlterField(
            model_name='brand',
            name='os',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.Os'),
        ),
    ]
