# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-26 18:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0010_auto_20161226_1846'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='is_tablet',
            new_name='type',
        ),
        migrations.AlterField(
            model_name='brand',
            name='os',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.Os'),
        ),
    ]
