# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20161226_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='hearts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='topic',
            name='hearts',
            field=models.IntegerField(default=0),
        ),
    ]
